### ISSUE TITLE
face lock

### ISSUE THREAD

**Issue by singhrash23** [shantamsultania/face-lock-#1]
facelock1.py is running successfully but while running facelock2.py it sends error.
![Screenshot (140)](https://user-images.githubusercontent.com/55138485/83349852-6e855180-a355-11ea-817b-bc3157b25533.png)

**Comment by shantamsultania** [comment]
Happy to see my first issue 
Just replace
‘./data_collection/'
With datacollection 
And you are done thats just because of change in name of of the folder 
I by mistakenly forgot to change it in facelook2.py
